-- Fresh-schema baseline for the first admin content domains.
-- Run this file once in the Supabase SQL Editor after resetting the public schema.
-- Do not also apply the same schema through a migration in the same environment.
-- Afterward, run enable_admin_login.sql once for the intended administrator.
-- Run seed_products.sql when the spreadsheet-backed draft product catalog is needed.

begin;

create extension if not exists pgcrypto;

-- -----------------------------------------------------------------------------
-- Tables
-- -----------------------------------------------------------------------------

create table public.products (
  id uuid primary key default gen_random_uuid(),
  product_type text not null,
  status text not null default 'draft'
    check (status in ('draft', 'published')),
  configuration jsonb not null default '{"variants": {}}'::jsonb
    check (
      jsonb_typeof(configuration) = 'object'
      and configuration ? 'variants'
      and jsonb_typeof(configuration -> 'variants') = 'object'
    ),
  sort_order bigint generated by default as identity,
  created_at timestamptz not null default now(),
  unique (product_type)
);

create table public.posts (
  id uuid primary key default gen_random_uuid(),
  kind text not null
    check (kind in ('blog', 'notice')),
  type text not null,
  title text not null,
  slug text not null,
  content text not null,
  content_mode text not null default 'html',
  content_authoring_mode text not null default 'raw_html',
  content_json jsonb,
  content_schema_version integer not null default 1,
  content_source_backup text,
  content_asset_scope uuid not null default gen_random_uuid(),
  excerpt text,
  thumbnail_path text,
  thumbnail_file_name text,
  thumbnail_alt text,
  seo_description text,
  status text not null default 'draft'
    check (status in ('draft', 'published')),
  published_at timestamptz not null default now(),
  show_on_landing boolean not null default false,
  show_as_banner boolean not null default false,
  featured boolean not null default false,
  pinned boolean not null default false,
  view_count bigint not null default 0
    check (view_count >= 0),
  sort_order bigint generated by default as identity,
  created_at timestamptz not null default now(),
  unique (kind, slug),
  check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  constraint posts_thumbnail_alt_requires_path
    check (thumbnail_path is not null or thumbnail_alt is null),
  constraint posts_thumbnail_file_name_requires_path
    check (
      thumbnail_file_name is null
      or (
        thumbnail_path is not null
        and nullif(btrim(thumbnail_file_name), '') is not null
      )
    ),
  constraint posts_content_mode_check
    check (content_mode in ('html', 'markdown')),
  constraint posts_content_authoring_mode_check
    check (content_authoring_mode in ('raw_html', 'wysiwyg')),
  constraint posts_content_schema_version_check
    check (content_schema_version = 1),
  constraint posts_wysiwyg_content_document_check
    check (
      content_authoring_mode <> 'wysiwyg'
      or (
        content_mode = 'html'
        and content_json is not null
        and jsonb_typeof(content_json) = 'object'
        and coalesce(content_json ->> 'type' = 'doc', false)
      )
    ),
  check (kind <> 'notice' or nullif(btrim(excerpt), '') is not null)
);

create table public.portfolio_items (
  id uuid primary key default gen_random_uuid(),
  type text not null,
  title text not null,
  slug text not null unique,
  client_name text,
  images jsonb not null default '[]'::jsonb
    check (jsonb_typeof(images) = 'array'),
  content text not null,
  content_mode text not null default 'html',
  content_authoring_mode text not null default 'raw_html',
  content_json jsonb,
  content_schema_version integer not null default 1,
  content_source_backup text,
  content_asset_scope uuid not null default gen_random_uuid(),
  show_on_landing boolean not null default false,
  pinned boolean not null default false,
  status text not null default 'draft'
    check (status in ('draft', 'published', 'archived')),
  published_at timestamptz,
  view_count bigint not null default 0
    check (view_count >= 0),
  sort_order bigint generated by default as identity,
  created_at timestamptz not null default now(),
  check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  check (
    status <> 'published'
    or (published_at is not null and jsonb_array_length(images) > 0)
  ),
  constraint portfolio_items_content_mode_check
    check (content_mode in ('html', 'markdown')),
  constraint portfolio_items_content_authoring_mode_check
    check (content_authoring_mode in ('raw_html', 'wysiwyg')),
  constraint portfolio_items_content_schema_version_check
    check (content_schema_version = 1),
  constraint portfolio_items_wysiwyg_content_document_check
    check (
      content_authoring_mode <> 'wysiwyg'
      or (
        content_mode = 'html'
        and content_json is not null
        and jsonb_typeof(content_json) = 'object'
        and coalesce(content_json ->> 'type' = 'doc', false)
      )
    )
);

create table public.reviews (
  id uuid primary key default gen_random_uuid(),
  kind text not null
    check (kind in ('interview', 'testimonial')),
  company_name text not null,
  manager_name text,
  project_deliverable text,
  project_usage text,
  title text,
  slug text,
  video_path text,
  youtube_video_id text,
  video_alt text,
  seo_description text,
  content text not null,
  content_mode text not null default 'html',
  content_authoring_mode text not null default 'raw_html',
  content_json jsonb,
  content_schema_version integer not null default 1,
  content_source_backup text,
  content_asset_scope uuid not null default gen_random_uuid(),
  show_on_landing boolean not null default false,
  status text not null default 'draft'
    check (status in ('draft', 'published', 'archived')),
  published_at timestamptz,
  view_count bigint not null default 0
    check (view_count >= 0),
  sort_order bigint generated by default as identity,
  created_at timestamptz not null default now(),
  check (slug is null or slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  constraint reviews_youtube_video_id_format_check
    check (
      youtube_video_id is null
      or youtube_video_id ~ '^[A-Za-z0-9_-]{11}$'
    ),
  constraint reviews_video_source_check
    check (
      nullif(btrim(video_path), '') is null
      or youtube_video_id is null
    ),
  constraint reviews_project_deliverable_nonblank_check
    check (
      project_deliverable is null
      or nullif(btrim(project_deliverable), '') is not null
    ),
  constraint reviews_project_usage_nonblank_check
    check (
      project_usage is null
      or nullif(btrim(project_usage), '') is not null
    ),
  constraint reviews_published_interview_project_info_check
    check (
      kind <> 'interview'
      or status <> 'published'
      or (
        nullif(btrim(project_deliverable), '') is not null
        and nullif(btrim(project_usage), '') is not null
      )
    ),
  constraint reviews_published_interview_video_check check (
    kind <> 'interview'
    or status <> 'published'
    or (
      nullif(btrim(title), '') is not null
      and nullif(btrim(slug), '') is not null
      and (
        nullif(btrim(video_path), '') is not null
        or youtube_video_id is not null
      )
      and published_at is not null
    )
  ),
  check (
    kind <> 'testimonial'
    or status <> 'published'
    or published_at is not null
  ),
  constraint reviews_content_mode_check
    check (content_mode in ('html', 'markdown')),
  constraint reviews_content_authoring_mode_check
    check (content_authoring_mode in ('raw_html', 'wysiwyg')),
  constraint reviews_content_schema_version_check
    check (content_schema_version = 1),
  constraint reviews_wysiwyg_content_document_check
    check (
      content_authoring_mode <> 'wysiwyg'
      or (
        content_mode = 'html'
        and content_json is not null
        and jsonb_typeof(content_json) = 'object'
        and coalesce(content_json ->> 'type' = 'doc', false)
      )
    )
);

create unique index reviews_interview_slug_key
  on public.reviews (slug)
  where kind = 'interview' and slug is not null;

create table public.complaints (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  email text,
  phone text not null,
  service text not null,
  complaint_type text not null,
  content text not null,
  phone_verified boolean not null default false,
  privacy_agreed_at timestamptz not null,
  status text not null default 'received'
    check (status in ('received', 'processing', 'resolved')),
  created_at timestamptz not null default now()
);

create table public.complaint_attachments (
  id uuid primary key default gen_random_uuid(),
  complaint_id uuid not null
    references public.complaints (id) on delete cascade,
  bucket_id text not null default 'private-attachments'
    check (bucket_id = 'private-attachments'),
  object_path text not null,
  original_file_name text not null,
  file_size bigint not null
    check (file_size > 0),
  content_type text not null,
  created_at timestamptz not null default now(),
  unique (bucket_id, object_path)
);

-- -----------------------------------------------------------------------------
-- Indexes used by the admin lists and published content queries
-- -----------------------------------------------------------------------------

create index products_status_sort_order_idx
  on public.products (status, sort_order);

create index posts_kind_status_published_at_idx
  on public.posts (kind, status, published_at desc);

create index posts_kind_sort_order_idx
  on public.posts (kind, sort_order);

create index portfolio_items_status_sort_order_idx
  on public.portfolio_items (status, sort_order);

create index reviews_kind_status_sort_order_idx
  on public.reviews (kind, status, sort_order);

create index complaints_status_created_at_idx
  on public.complaints (status, created_at desc);

create index complaint_attachments_complaint_id_idx
  on public.complaint_attachments (complaint_id);

-- -----------------------------------------------------------------------------
-- Reordering RPCs
-- Each RPC accepts the complete ordered ID list for its list.
-- -----------------------------------------------------------------------------

create or replace function public.reorder_products(product_ids uuid[])
returns void
language plpgsql
security invoker
set search_path = ''
as $$
begin
  if coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '') <> 'admin' then
    raise exception 'admin role required' using errcode = '42501';
  end if;

  if coalesce(cardinality(product_ids), -1)
       <> (select count(*)::integer from public.products)
     or (select count(distinct item_id) from unnest(product_ids) as ids(item_id))
       <> coalesce(cardinality(product_ids), -1)
     or exists (
       select 1
       from unnest(product_ids) as ids(item_id)
       left join public.products as product on product.id = ids.item_id
       where product.id is null
     ) then
    raise exception 'product_ids must contain every product exactly once';
  end if;

  update public.products as product
  set sort_order = ordered.position
  from unnest(product_ids) with ordinality as ordered(id, position)
  where product.id = ordered.id;
end;
$$;

create or replace function public.reorder_posts(post_kind text, post_ids uuid[])
returns void
language plpgsql
security invoker
set search_path = ''
as $$
begin
  if coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '') <> 'admin' then
    raise exception 'admin role required' using errcode = '42501';
  end if;

  if post_kind not in ('blog', 'notice') then
    raise exception 'unsupported post kind';
  end if;

  if coalesce(cardinality(post_ids), -1)
       <> (
         select count(*)::integer
         from public.posts
         where kind = post_kind
       )
     or (select count(distinct item_id) from unnest(post_ids) as ids(item_id))
       <> coalesce(cardinality(post_ids), -1)
     or exists (
       select 1
       from unnest(post_ids) as ids(item_id)
       left join public.posts as post
         on post.id = ids.item_id
        and post.kind = post_kind
       where post.id is null
     ) then
    raise exception 'post_ids must contain every post of this kind exactly once';
  end if;

  update public.posts as post
  set sort_order = ordered.position
  from unnest(post_ids) with ordinality as ordered(id, position)
  where post.id = ordered.id
    and post.kind = post_kind;
end;
$$;

create or replace function public.reorder_portfolio_items(portfolio_item_ids uuid[])
returns void
language plpgsql
security invoker
set search_path = ''
as $$
begin
  if coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '') <> 'admin' then
    raise exception 'admin role required' using errcode = '42501';
  end if;

  if coalesce(cardinality(portfolio_item_ids), -1)
       <> (select count(*)::integer from public.portfolio_items)
     or (
       select count(distinct item_id)
       from unnest(portfolio_item_ids) as ids(item_id)
     ) <> coalesce(cardinality(portfolio_item_ids), -1)
     or exists (
       select 1
       from unnest(portfolio_item_ids) as ids(item_id)
       left join public.portfolio_items as portfolio_item
         on portfolio_item.id = ids.item_id
       where portfolio_item.id is null
     ) then
    raise exception 'portfolio_item_ids must contain every portfolio item exactly once';
  end if;

  update public.portfolio_items as portfolio_item
  set sort_order = ordered.position
  from unnest(portfolio_item_ids) with ordinality as ordered(id, position)
  where portfolio_item.id = ordered.id;
end;
$$;

create or replace function public.reorder_reviews(review_ids uuid[])
returns void
language plpgsql
security invoker
set search_path = ''
as $$
begin
  if coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '') <> 'admin' then
    raise exception 'admin role required' using errcode = '42501';
  end if;

  if coalesce(cardinality(review_ids), -1)
       <> (select count(*)::integer from public.reviews)
     or (select count(distinct item_id) from unnest(review_ids) as ids(item_id))
       <> coalesce(cardinality(review_ids), -1)
     or exists (
       select 1
       from unnest(review_ids) as ids(item_id)
       left join public.reviews as review on review.id = ids.item_id
       where review.id is null
     ) then
    raise exception 'review_ids must contain every review exactly once';
  end if;

  update public.reviews as review
  set sort_order = ordered.position
  from unnest(review_ids) with ordinality as ordered(id, position)
  where review.id = ordered.id;
end;
$$;

create or replace function public.increment_content_view(
  p_content_type text,
  p_content_id uuid
)
returns void
language plpgsql
security invoker
set search_path = ''
as $$
begin
  case p_content_type
    when 'blog' then
      update public.posts
      set view_count = view_count + 1
      where id = p_content_id
        and kind = 'blog'
        and status = 'published';
    when 'portfolio' then
      update public.portfolio_items
      set view_count = view_count + 1
      where id = p_content_id
        and status = 'published';
    when 'interview' then
      update public.reviews
      set view_count = view_count + 1
      where id = p_content_id
        and kind = 'interview'
        and status = 'published';
    else
      raise exception 'unsupported content view type: %', p_content_type
        using errcode = '22023';
  end case;
end;
$$;

-- Content asset scopes bind public rich-content URLs to a single record.
-- Regular saves may resubmit the same value, but a persisted record cannot
-- take ownership of another scope.
create or replace function public.prevent_content_asset_scope_change()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if new.content_asset_scope is distinct from old.content_asset_scope then
    raise exception 'content_asset_scope is immutable';
  end if;

  return new;
end;
$$;

revoke execute on function public.prevent_content_asset_scope_change()
from public, anon, authenticated;

create trigger posts_prevent_content_asset_scope_change
before update of content_asset_scope on public.posts
for each row
execute function public.prevent_content_asset_scope_change();

create trigger portfolio_items_prevent_content_asset_scope_change
before update of content_asset_scope on public.portfolio_items
for each row
execute function public.prevent_content_asset_scope_change();

create trigger reviews_prevent_content_asset_scope_change
before update of content_asset_scope on public.reviews
for each row
execute function public.prevent_content_asset_scope_change();

-- -----------------------------------------------------------------------------
-- Row Level Security
-- Admin authorization uses auth.users.raw_app_meta_data through auth.jwt().
-- -----------------------------------------------------------------------------

alter table public.products enable row level security;
alter table public.posts enable row level security;
alter table public.portfolio_items enable row level security;
alter table public.reviews enable row level security;
alter table public.complaints enable row level security;
alter table public.complaint_attachments enable row level security;

create policy products_public_read_published
on public.products
for select
to anon, authenticated
using (status = 'published');

create policy products_admin_manage
on public.products
for all
to authenticated
using ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
with check ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

create policy posts_public_read_published
on public.posts
for select
to anon
using (status = 'published');

create policy posts_admin_manage
on public.posts
for all
to authenticated
using ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
with check ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

create policy portfolio_items_public_read_published
on public.portfolio_items
for select
to anon
using (status = 'published');

create policy portfolio_items_admin_manage
on public.portfolio_items
for all
to authenticated
using ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
with check ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

create policy reviews_public_read_published
on public.reviews
for select
to anon
using (status = 'published');

create policy reviews_admin_manage
on public.reviews
for all
to authenticated
using ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
with check ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

create policy complaints_admin_read
on public.complaints
for select
to authenticated
using ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

create policy complaints_admin_update_status
on public.complaints
for update
to authenticated
using ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
with check ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

create policy complaint_attachments_admin_read
on public.complaint_attachments
for select
to authenticated
using ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

-- -----------------------------------------------------------------------------
-- Explicit API privileges
-- RLS still decides which rows authenticated callers may access.
-- -----------------------------------------------------------------------------

revoke all privileges on all tables in schema public
from public, anon, authenticated;

revoke all privileges on all sequences in schema public
from public, anon, authenticated;

revoke all privileges on all functions in schema public
from public, anon, authenticated;

grant usage on schema public to anon, authenticated, service_role;

grant select on public.products to anon;

revoke all privileges on table public.posts, public.portfolio_items, public.reviews
from public, anon;

grant select (
  id, kind, type, title, slug, content, content_mode, content_authoring_mode,
  content_asset_scope, excerpt, thumbnail_path, thumbnail_alt, seo_description,
  status, published_at, show_on_landing, show_as_banner, featured, pinned,
  view_count, sort_order, created_at
) on public.posts to anon;

grant select (
  id, type, title, slug, client_name, images, content, content_mode,
  content_authoring_mode, content_asset_scope, show_on_landing, pinned, status,
  published_at, view_count, sort_order, created_at
) on public.portfolio_items to anon;

grant select (
  id, kind, company_name, manager_name, project_deliverable, project_usage, title,
  slug, video_path, youtube_video_id, video_alt, seo_description, content,
  content_mode, content_authoring_mode, content_asset_scope, show_on_landing,
  status, published_at, view_count, sort_order, created_at
) on public.reviews to anon;

grant select, insert, update, delete
on public.products,
   public.posts,
   public.portfolio_items,
   public.reviews
to authenticated;

grant all privileges on table public.posts, public.portfolio_items, public.reviews
to service_role;

grant select on public.complaints, public.complaint_attachments
to authenticated;

grant update (status) on public.complaints
to authenticated;

grant all privileges on all tables in schema public to service_role;
grant usage, select on all sequences in schema public to authenticated, service_role;
grant all privileges on all functions in schema public to service_role;

grant execute
on function public.reorder_products(uuid[]),
            public.reorder_posts(text, uuid[]),
            public.reorder_portfolio_items(uuid[]),
            public.reorder_reviews(uuid[])
to authenticated;

-- -----------------------------------------------------------------------------
-- Storage
-- public-assets: thumbnails, portfolio images, and interview videos.
-- private-attachments: complaint attachments; never exposed as a public bucket.
-- -----------------------------------------------------------------------------

insert into storage.buckets (
  id,
  name,
  public,
  file_size_limit,
  allowed_mime_types
)
values (
  'public-assets',
  'public-assets',
  true,
  524288000,
  array[
    'image/jpeg',
    'image/png',
    'image/webp',
    'video/mp4',
    'video/quicktime'
  ]
)
on conflict (id) do update
set name = excluded.name,
    public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

insert into storage.buckets (
  id,
  name,
  public,
  file_size_limit,
  allowed_mime_types
)
values (
  'private-attachments',
  'private-attachments',
  false,
  52428800,
  array[
    'image/jpeg',
    'image/png',
    'image/webp'
  ]
)
on conflict (id) do update
set name = excluded.name,
    public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists public_assets_admin_read on storage.objects;
drop policy if exists public_assets_admin_insert on storage.objects;
drop policy if exists public_assets_admin_update on storage.objects;
drop policy if exists public_assets_admin_delete on storage.objects;
drop policy if exists private_attachments_admin_read on storage.objects;

create policy public_assets_admin_read
on storage.objects
for select
to authenticated
using (
  bucket_id = 'public-assets'
  and (select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin'
);

create policy public_assets_admin_insert
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'public-assets'
  and (select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin'
);

create policy public_assets_admin_update
on storage.objects
for update
to authenticated
using (
  bucket_id = 'public-assets'
  and (select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin'
)
with check (
  bucket_id = 'public-assets'
  and (select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin'
);

create policy public_assets_admin_delete
on storage.objects
for delete
to authenticated
using (
  bucket_id = 'public-assets'
  and (select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin'
);

create policy private_attachments_admin_read
on storage.objects
for select
to authenticated
using (
  bucket_id = 'private-attachments'
  and (select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin'
);

notify pgrst, 'reload schema';

commit;
