const COMPLAINT_ATTACHMENT_BYTES_IN_KILOBYTE = 1024;
const COMPLAINT_ATTACHMENT_BYTES_IN_MEGABYTE =
  COMPLAINT_ATTACHMENT_BYTES_IN_KILOBYTE * 1024;

export const MAX_COMPLAINT_ATTACHMENT_COUNT = 10;
export const MAX_COMPLAINT_ATTACHMENT_SIZE_BYTES =
  50 * COMPLAINT_ATTACHMENT_BYTES_IN_MEGABYTE;
